# Generated by Django 5.1.1 on 2024-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicClustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('rating', models.IntegerField(default=5)),
                ('genre', models.CharField(default='', max_length=200)),
                ('artist_name', models.CharField(default='', max_length=200)),
                ('valence', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('popularity', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('tempo', models.IntegerField(default=5)),
            ],
        ),
    ]
