# Generated by Django 5.1.1 on 2024-10-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_clustering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('genre', models.CharField(default='', max_length=200)),
                ('artist_name', models.CharField(default='', max_length=200)),
                ('valence', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('popularity', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('tempo', models.IntegerField(default=5)),
            ],
        ),
        migrations.DeleteModel(
            name='MusicClustering',
        ),
        migrations.AddField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_clustering.song'),
        ),
    ]
