# Generated by Django 5.1.1 on 2024-11-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_clustering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img_src',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
