# Generated by Django 5.1.1 on 2024-10-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_clustering', '0002_rating_song_delete_musicclustering_rating_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=200)),
                ('spotify_display_name', models.CharField(max_length=200)),
            ],
        ),
    ]
