# Generated by Django 5.1.1 on 2024-11-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_clustering', '0002_song_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='rated_by',
            field=models.ManyToManyField(blank=True, to='music_clustering.user'),
        ),
    ]
