# Generated by Django 5.1.1 on 2024-10-05 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_clustering', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music_clustering.user'),
            preserve_default=False,
        ),
    ]
